// This file is autogenerated. Changes will be overwritten.
#include "F2YV4FKCGW/moc_canvas.cpp"
#include "F2YV4FKCGW/moc_gain_input_dialog.cpp"
#include "F2YV4FKCGW/moc_output.cpp"
#include "F2YV4FKCGW/moc_toolbar.cpp"
#include "F2YV4FKCGW/moc_validation_dialog.cpp"
#include "BORQOY2OT6/moc_mainwindow.cpp"
